### ISSUE TITLE
Category does not exist

### ISSUE THREAD

**Issue by liloo2040** [gregurco/jobeet-tutorial#15]
Hi! 

I'm currently doing your tutorial, I'm on Day 7 (you need to add your missing comma on your tutorial right before $page on CategoryController.php on function show() ).

I have currently an issue, when I go to the main page ("/") it says that none of the methods like activeJobs() exists and have a public access in class App\Entity\Category.

Do you have a fix for this ?  Thank you!

**Comment by liloo2040** [comment]
Closing the issue, I've found the fix!

**Comment by gregurco** [comment]
@liloo2040 what was the problem? Do you have any suggestions to improve the guide, somebody not to have the same problem?

**Comment by slash3b** [comment]
@liloo2040  confess to us!

**Comment by liloo2040** [comment]
I had issues, I found them and fixed them.
