### ISSUE TITLE
Day 10 : The Admin - Delete job action fix

### ISSUE THREAD

**Issue by liloo2040** [gregurco/jobeet-tutorial#20]
Hi!

Just one small tip, there is an issue on your tutorial in "The admin", Job section, delete action on controller. 

Instead of adding `@param Job $job` and adding `Job $job`, in your parameters in your delete action, you added `@param Category $category` and `Category $category` there.

I tried to make it work as said in your tutorial (with `Category $category` in controller) and it didn't. So, I replaced it with `Job $job`. (As I noticed that most of actions in the JobController required `Job $job`)

Can you replace this in your tutorial ? Thank you !

**Comment by gregurco** [comment]
Hello.
Yep, you are right. It's really strange, because in code we have correct version: https://github.com/gregurco/jobeet/blob/day10/src/Controller/Admin/JobController.php#L105

I fixed it in PR #10.

Thank you :+1:

**Comment by liloo2040** [comment]
You're welcome ! ;-)
