### ISSUE TITLE
Day 7 - Wrong variable name in List Pagination paragraph

### ISSUE THREAD

**Issue by gracoes** [gregurco/jobeet-tutorial#36]
Close to the end of the paragraph there is this text.  
We added page in the URL path and defined default value, in case when page is not defined in the URL (ex: /category/design). Variable **$path** is added in arguments of the method. It will be injected automatically by name in path. Also we need parameter max_jobs_on_category and getParameter methods to access it. That’s why this controller extends now Symfony\Bundle\FrameworkBundle\Controller\Controller but not Symfony\Bundle\FrameworkBundle\Controller\AbstractController.

Shouldn't it be the $page variable?

**Comment by gregurco** [comment]
@gracoes yes, you are right. Fixed in PR #40. Thank you for reporting :+1:
