### ISSUE TITLE
Show job route

### ISSUE THREAD

**Issue by dmclark** [gregurco/jobeet-tutorial#5]
First, thanks  so much for taking this on!

I'm not 100% sure about this, but on day 5:

> the wildcard * which stands for ID in the given example

there is no * in the code above it

**Comment by gregurco** [comment]
Hello @dmclark. Thank you for the feedback.
Yep, there was a small obscurity with some definitions. I rewrote a part this paragraph. Please take a look here: https://github.com/gregurco/jobeet-tutorial/blob/improve_day_5/docs/days/day-5.md#routing-configuration
How do you think, it's more clear now?

The diff is in PR #6.
